# Generated by Django 4.1.8 on 2023-07-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Champion_stats",
            fields=[
                (
                    "name",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("hp", models.IntegerField()),
                ("hp_perlevel", models.IntegerField()),
                ("mp", models.IntegerField()),
                ("mp_perlevel", models.IntegerField()),
                ("armor", models.IntegerField()),
                ("armor_perlevel", models.IntegerField()),
                ("spellblock", models.IntegerField()),
                ("spellblock_perlevel", models.IntegerField()),
                ("hpregen", models.IntegerField()),
                ("hpregen_perlevel", models.IntegerField()),
                ("mpregen", models.IntegerField()),
                ("mpregen_perlevel", models.IntegerField()),
                ("crit", models.IntegerField()),
                ("crit_perlevel", models.IntegerField()),
                ("attackdamage", models.IntegerField()),
                ("attackdamage_perlevel", models.IntegerField()),
                ("attackspeed", models.IntegerField()),
                ("attackspeed_perlevel", models.IntegerField()),
            ],
        ),
    ]
