name: deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      working-directory: ./frontend
      env:
        MY_EMAIL: craycoding@gmail.com
        MY_NAME: crAy
      run: |
        git config --global user.email $MY_EMAIL
        git config --global user.name $MY_NAME
        git remote set-url origin https://BAD-MDC:${{ secrets.BAD_MDC_PASSWORD }}@github.com/BAD-MDC/loldamagesimulator.git
        npm install
        npm install -g gh-pages
        npm run deploy
